### ISSUE TITLE
Controller not initialized until user goes through world generation

### ISSUE THREAD

**Issue by OrionFive** [KiameV/rimworld-factioncontrol#17]
I have (finally) found out why Faction Control conflicts with my mod Faction Discovery.

Faction Control patches **TileFinder_RandomFactionBaseTileFor**. But unless the user has been in the world generation menu, **Controller.maxFactionSprawl**, **Controller.pirateSprawl** and **Controller.minFactionSeparation** are all zero. So **TileFinder_RandomFactionBaseTileFor** doesn't return any available tiles when used later.

Could you please ensure that your **Controller** class is initialized when a game has been loaded?

Thanks in advance,
Orion

**Comment by KiameV** [comment]
OH. So this is only for the case when the user is Loading a saved game. Makes sense.

**Comment by KiameV** [comment]
Pushed the change on Steam and updated here. For those manually downloading they'll need Faction Control modsync/hugslib version 1.1.2.2

Please reopen if there's still a problem.

**Comment by OrionFive** [comment]
Thanks for the fast fix! That was lightning speed!
It works fine now.
