### ISSUE TITLE
I can't find the setting to customize the amount of modded factions after the update. I know that there is a vanilla way to do that but it doesn't display half of the modded factions factions. I tried "Override Faction Max Count" on, after reloading the game they weren't there, after I set it to off, they weren't there either. I also don't understand what "Disable Faction Limits" does, I didn't understand what its description meant, but either way, it also didn't cause the modded factions to show up.   So I've reloaded the game while my "Override Faction Max Count" was on, I disabled every faction in the vanilla menu, but some factions are not in vanilla menu and for some reason I didn't find this mods menu to disable them anywhere. This includes factions from Star Wars - Hutts, Star Wars - Gand, Star Wars - Trandosha, The GiantRace, two factions from Halo Jackals. I couldn't find any ways disable them.

### ISSUE THREAD

**Issue by inikishev** [KiameV/rimworld-factioncontrol#19]
I can't find the setting to customize the amount of modded factions after the update. I know that there is a vanilla way to do that but it doesn't display half of the modded factions factions. I tried "Override Faction Max Count" on, after reloading the game they weren't there, after I set it to off, they weren't there either. I also don't understand what "Disable Faction Limits" does, I didn't understand what its description meant, but either way, it also didn't cause the modded factions to show up. 

So I've reloaded the game while my "Override Faction Max Count" was on, I disabled every faction in the vanilla menu, but some factions are not in vanilla menu and for some reason I didn't find this mods menu to disable them anywhere. This includes factions from Star Wars - Hutts, Star Wars - Gand, Star Wars - Trandosha, The GiantRace, two factions from Halo Jackals. I couldn't find any ways disable them.

Other modded factions do show up in the menu, for example Mantodean, Rim-Effect, Folia, Quartzian, Fimir, Gor, etc.
https://gist.github.com/idkman2021/d88c2cf488eed817d8ea1ee4e0e836b5

**Comment by KiameV** [comment]
The setting for Override Faction Max Count is really just me trying to fix other people's stuff for them.

If that doesn't do anything then the authors of those mod simply have to add `<maxConfigurableAtWorldCreation>9999</maxConfigurableAtWorldCreation>` to their faction's def. Simple as that.

**Comment by inikishev** [comment]
> The setting for Override Faction Max Count is really just me trying to fix other people's stuff for them.
> 
> If that doesn't do anything then the authors of those mod simply have to add `<maxConfigurableAtWorldCreation>9999</maxConfigurableAtWorldCreation>` to their faction's def. Simple as that.

I just made a patch to do that. I am assuming faction control also has a patch and it needs to be loaded after mods that don't have this thing in theor faction def?

```
<?xml version="1.0" encoding="utf-8"?>
<Patch>
<Operation Class="PatchOperationAdd">
    <xpath>/Defs/FactionDef[defName and not(maxConfigurableAtWorldCreation) and not(hidden="true") and not(isPlayer="true") and(@ParentName="FactionBase" or not(@ParentName))]</xpath>
    <value>
    <maxConfigurableAtWorldCreation>9999</maxConfigurableAtWorldCreation>
    </value>
</Operation>
<Operation Class="PatchOperationFindMod">
    <mods>
        <li>The GiantRace</li>
    </mods>
    <match Class="PatchOperationAdd">
    <xpath>/Defs/FactionDef[(defName="SavageGiants") and not(maxConfigurableAtWorldCreation)]</xpath>
    	<value>
    		<maxConfigurableAtWorldCreation>9999</maxConfigurableAtWorldCreation>
    	</value>
    </match>
</Operation>
</Patch>
```
Alright this seems to be the only way to not catch anything that shouldn't be in the faction selection menu
